package Codes;

import java.awt.Color;

/**
 *
 * @author Bryan Ferrais
 * @version DEMO 1.0
 * @since 2019
 */
public class Mainframe extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */
    public Mainframe() {
        initComponents();
        lblError.setVisible(false);
        nrecSpin.setVisible(false);
        lblNrec.setVisible(false);
        nrecAproved.setVisible(false);
        btnNrec.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n1Spin = new javax.swing.JSpinner();
        n2Spin = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblMedia = new javax.swing.JLabel();
        lblAproved = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nrecSpin = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        lblNrec = new javax.swing.JLabel();
        btnNrec = new javax.swing.JButton();
        nrecAproved = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("N1:");

        jLabel2.setText("N2:");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Media:");

        lblMedia.setText("0");

        lblAproved.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel4.setText("NREC:");

        jLabel5.setText("Media com NREC:");

        lblNrec.setText("0");

        btnNrec.setText("Calcular");
        btnNrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNrecActionPerformed(evt);
            }
        });

        nrecAproved.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nrecAproved.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblError.setBackground(new java.awt.Color(0, 0, 0));
        lblError.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("ERRO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(n1Spin, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                            .addComponent(n2Spin))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(nrecSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnNrec))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblNrec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblAproved, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(nrecAproved, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n1Spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n2Spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAproved, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jLabel3)
                                .addComponent(lblMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nrecSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblNrec)
                    .addComponent(btnNrec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nrecAproved, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n1 = Integer.parseInt(n1Spin.getValue().toString());
        int n2 = Integer.parseInt(n2Spin.getValue().toString());
        int media = (n1+n2)/2;
        int nrec = Integer.parseInt(nrecSpin.getValue().toString());
        byte btnpress;
        
        btnpress = 1;
        lblError.setVisible(false);
        lblMedia.setText(Integer.toString(media));
        
        
        if(n1 < 0){
            lblError.setVisible(true);
            lblError.setText("N1 menor que 0.");
            
            nrecSpin.setVisible(false);
            lblNrec.setVisible(false);
            nrecAproved.setVisible(false);
            btnNrec.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            btnpress = 0;
        }
        else if(n1 > 10){
            lblError.setVisible(true);
            lblError.setText("N1 maior que 10.");
            
            nrecSpin.setVisible(false);
            lblNrec.setVisible(false);
            nrecAproved.setVisible(false);
            btnNrec.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            btnpress = 0;
        }
        else if(n2 > 10){
            lblError.setVisible(true);
            lblError.setText("N2 maior que 10.");
            
            nrecSpin.setVisible(false);
            lblNrec.setVisible(false);
            nrecAproved.setVisible(false);
            btnNrec.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            btnpress = 0;
        }
        else if(n2 < 0){
            lblError.setVisible(true);
            lblError.setText("N2 menor que 0.");
            
            nrecSpin.setVisible(false);
            lblNrec.setVisible(false);
            nrecAproved.setVisible(false);
            btnNrec.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            btnpress = 0;
        }
        
        while(btnpress == 1){   
        if(media >= 6){
            lblAproved.setForeground(Color.green);
            lblAproved.setText("APROVADO.");
            
            nrecSpin.setVisible(false);
            lblNrec.setVisible(false);
            nrecAproved.setVisible(false);
            btnNrec.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            btnpress = 0;
        }
        else{
            lblAproved.setForeground(Color.red);
            lblAproved.setText("RECUPERAÇÃO.");
            
            nrecSpin.setVisible(true);
            lblNrec.setVisible(true);
            nrecAproved.setVisible(true);
            btnNrec.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            btnpress = 0;
        }       
        }//while
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNrecActionPerformed
        int n1 = Integer.parseInt(n1Spin.getValue().toString());
        int n2 = Integer.parseInt(n2Spin.getValue().toString());
        int nrec = Integer.parseInt(nrecSpin.getValue().toString());
        int nrecap = 0;
        byte btnpress = 1;
        byte btnpressN = 1;
        
        //btnpress = 1;
        //btnpressN = 1;
        lblError.setVisible(false);
        //lblMedia.setText(Integer.toString(nrecap));
        
        if(nrec < 0){
            lblError.setVisible(true);
            lblError.setText("NREC menor que 0.");
            btnpress = 0;
            btnpressN = 0;
        }
        else if(nrec > 10){
            lblError.setVisible(true);
            lblError.setText("NREC maior que 10.");
            btnpress = 0;
            btnpressN = 0;
        }
        
        while(btnpress == 1){
            if(nrec > n1 || nrec > n2){
                if(n1 > n2){
                  nrecap = (nrec + n1)/2;
                  lblNrec.setText(Integer.toString(nrecap));
                  btnpress = 0;
                }
                else if(n2 > n1){
                  nrecap = (nrec + n2)/2;            
                  lblNrec.setText(Integer.toString(nrecap));
                  btnpress = 0;
                }
                else if(n1 == n2){
                  nrecap = (nrec + n1)/2;
                  lblNrec.setText(Integer.toString(nrecap));
                  btnpress = 0;   
                } 
            }//if
            else{
                btnpress = 0;
            }                  
        }//while
        while(btnpressN == 1){   
        if(nrecap >= 6){
            nrecAproved.setForeground(Color.green);
            nrecAproved.setText("APROVADO COM NREC.");
            btnpressN = 0;
        }
        else{
            nrecAproved.setForeground(Color.red);
            nrecAproved.setText("REPROVADO.");
            btnpressN = 0;
        }       
        }//while
    }//GEN-LAST:event_btnNrecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNrec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAproved;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblNrec;
    private javax.swing.JSpinner n1Spin;
    private javax.swing.JSpinner n2Spin;
    private javax.swing.JLabel nrecAproved;
    private javax.swing.JSpinner nrecSpin;
    // End of variables declaration//GEN-END:variables
}
